/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	objectstoragev1alpha1 "sigs.k8s.io/container-object-storage-interface/client/apis/objectstorage/v1alpha1"
	scheme "sigs.k8s.io/container-object-storage-interface/client/clientset/versioned/scheme"
)

// BucketAccessesGetter has a method to return a BucketAccessInterface.
// A group's client should implement this interface.
type BucketAccessesGetter interface {
	BucketAccesses(namespace string) BucketAccessInterface
}

// BucketAccessInterface has methods to work with BucketAccess resources.
type BucketAccessInterface interface {
	Create(ctx context.Context, bucketAccess *objectstoragev1alpha1.BucketAccess, opts v1.CreateOptions) (*objectstoragev1alpha1.BucketAccess, error)
	Update(ctx context.Context, bucketAccess *objectstoragev1alpha1.BucketAccess, opts v1.UpdateOptions) (*objectstoragev1alpha1.BucketAccess, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, bucketAccess *objectstoragev1alpha1.BucketAccess, opts v1.UpdateOptions) (*objectstoragev1alpha1.BucketAccess, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*objectstoragev1alpha1.BucketAccess, error)
	List(ctx context.Context, opts v1.ListOptions) (*objectstoragev1alpha1.BucketAccessList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *objectstoragev1alpha1.BucketAccess, err error)
	BucketAccessExpansion
}

// bucketAccesses implements BucketAccessInterface
type bucketAccesses struct {
	*gentype.ClientWithList[*objectstoragev1alpha1.BucketAccess, *objectstoragev1alpha1.BucketAccessList]
}

// newBucketAccesses returns a BucketAccesses
func newBucketAccesses(c *ObjectstorageV1alpha1Client, namespace string) *bucketAccesses {
	return &bucketAccesses{
		gentype.NewClientWithList[*objectstoragev1alpha1.BucketAccess, *objectstoragev1alpha1.BucketAccessList](
			"bucketaccesses",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *objectstoragev1alpha1.BucketAccess { return &objectstoragev1alpha1.BucketAccess{} },
			func() *objectstoragev1alpha1.BucketAccessList { return &objectstoragev1alpha1.BucketAccessList{} },
		),
	}
}
