/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	objectstoragev1alpha1 "sigs.k8s.io/container-object-storage-interface/client/apis/objectstorage/v1alpha1"
)

// BucketClassLister helps list BucketClasses.
// All objects returned here must be treated as read-only.
type BucketClassLister interface {
	// List lists all BucketClasses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*objectstoragev1alpha1.BucketClass, err error)
	// Get retrieves the BucketClass from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*objectstoragev1alpha1.BucketClass, error)
	BucketClassListerExpansion
}

// bucketClassLister implements the BucketClassLister interface.
type bucketClassLister struct {
	listers.ResourceIndexer[*objectstoragev1alpha1.BucketClass]
}

// NewBucketClassLister returns a new BucketClassLister.
func NewBucketClassLister(indexer cache.Indexer) BucketClassLister {
	return &bucketClassLister{listers.New[*objectstoragev1alpha1.BucketClass](indexer, objectstoragev1alpha1.Resource("bucketclass"))}
}
